name: ApplicationRequests
defType: ObjectOnly
imports:
  - ackcord.data._
innerTypes:
  - name: getCurrentApplication
    defType: Request
    method: GET
    path: [applications, '@me']
    return: Application