name: ApplicationRoleConnectionMetadataRequests
defType: ObjectOnly
innerTypes:
  - name: getApplicationRoleConnectionMetadataRecords
    defType: Request
    path: [applications, {argOf: ApplicationId}, role-connections, metadata]
    return: Seq[ApplicationRoleConnectionMetadata]

  - name: updateApplicationRoleConnectionMetadataRecords
    defType: Request
    path: [applications, {argOf: ApplicationId}, role-connections, metadata]
    body: Seq[ApplicationRoleConnectionMetadata]
    return: Seq[ApplicationRoleConnectionMetadata]