//noinspection ScalaWeakerAccess, ScalaUnusedSymbol, DuplicatedCode
package ackcord.requests

// THIS FILE IS MACHINE GENERATED!
//
// Do not edit this file directly.
// Instead, edit the file generated/ackcord/requests/VoiceRegionRequests.yaml

import ackcord.data._
import ackcord.data.base._
import io.circe.Json
import sttp.model.Method

object VoiceRegionRequests {

  /**
    * Returns an array of voice region objects that can be used when setting a
    * voice or stage channel's rtc_region.
    */
  val listVoiceRegions: Request[Unit, Seq[VoiceRegion]] =
    Request.restRequest(
      route = (Route.Empty / "voice" / "regions").toRequest(Method.GET)
    )
}
