name: AckCord CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt

      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Build and Test
        run: sbt -v +test
